
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "config.h"
#include "adw-enums-private.h"
#include "adw-settings-private.h"

#define C_ENUM(v) ((gint) v)
#define C_FLAGS(v) ((guint) v)

/* enumerations from "adw-settings-private.h" */

GType
adw_system_color_scheme_get_type (void)
{
static gsize gtype_id = 0;
static const GEnumValue values[] = {
    { C_ENUM(ADW_SYSTEM_COLOR_SCHEME_DEFAULT), "ADW_SYSTEM_COLOR_SCHEME_DEFAULT", "default" },
    { C_ENUM(ADW_SYSTEM_COLOR_SCHEME_PREFER_DARK), "ADW_SYSTEM_COLOR_SCHEME_PREFER_DARK", "prefer-dark" },
    { C_ENUM(ADW_SYSTEM_COLOR_SCHEME_PREFER_LIGHT), "ADW_SYSTEM_COLOR_SCHEME_PREFER_LIGHT", "prefer-light" },
{ 0, NULL, NULL }
        };
        if (g_once_init_enter (&gtype_id)) {
            GType new_type = g_enum_register_static (g_intern_static_string ("AdwSystemColorScheme"), values);
            g_once_init_leave (&gtype_id, new_type);
        }
        return (GType) gtype_id;
        }

/* Generated data ends here */

