
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #if !defined(_ADWAITA_INSIDE) && !defined(ADWAITA_COMPILATION)
#error "Only <adwaita.h> can be included directly."
#endif

#include "adw-enums.h"


            G_BEGIN_DECLS

/* enumerations from "adw-settings-private.h" */


GType adw_system_color_scheme_get_type (void);
#define ADW_TYPE_SYSTEM_COLOR_SCHEME (adw_system_color_scheme_get_type())

G_END_DECLS

/* Generated data ends here */

