/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "libadwaita"

#define LOCALEDIR "/usr/share/locale"

#define _ADW_EXTERN __attribute__((visibility("default"))) extern

